### ISSUE TITLE
Conflicting version of Access DB Engine Redistributable

### ISSUE THREAD

**Issue by RobBowman** [BTDF/DeploymentFramework#1]
Hi Tom, I've run into this problem several times but can't remember how I solved it! The BAMTypedDefinition exe requires the Access Database Engine 2010 Redistributable. My problem is, I can't get this to work with the 32bit version. It works 1st time with the 64bit version. However, the ExportBamDefinitionXml will only work with the 32bit version. So, currently I'm having to build my solution with the 64bit version installed, then uninstall and install the 32bit version before deploying the soltion - this hampers productivity a little! I'm running VS2013 / BTS201r2 and BTDF 5.6. The dev vm has Excel 2013 32bit installed.

**Comment by tfabraham** [comment]
I shipped GenerateTypedBamApi/ExportBamDefinitionXml with both x86 and x64 builds (a very long time ago).  BTDF *should* include the x86 version of each.  I had to do that thanks to the mutually-exclusive Office runtime install.  If I shipped an AnyCPU version, it may run as x64 and fail because the x64 Office runtime wasn't present.  Very annoying.

I can't say I've ever seen an error with an out-of-the-box BTDF and Office x86 installed.  I think what you're saying is that the two EXE's have different behavior.  Very odd since they are built with a lot of shared code.  One works with DB Engine x86, and the other works with DB Engine x64?

**Comment by RobBowman** [comment]
Hi Tom, I made a screencast to demonstrate the problem. I can't get the link to work from here so I've emailed to you.
Apologies for my verbal rambling - it's been a long week!

I wonder if this problem may be related to the fact BTDF 5.6 and 6 are installed?
Please let me know if there are any file versions I should check - or anything else I can do to try to get to the bottom of this!

**Comment by RobBowman** [comment]
Hi Tom, I closed all instances of VS, then from the "Programs and Features" section of control panel, I removed BTDF 5.6. There was no sign of BTDF 6 in here, so I simply deleted it from the "Program Files (x86)" folder. I then rebooted, downloaded BTDF 5.7 and installed. My problem now is, there's no sign of BTDF in VS2013, I can't select the toolbar and there's nothing in the Tools menu. Any ideas?

**Comment by tfabraham** [comment]
It’s on the Visual Studio Marketplace.

**Comment by RobBowman** [comment]
Thanks Tom. I have now installed to VS tools from the Gallery. I think for the earlier versions - the tools were installed by the main MSI? I'm sure I should have know about the Marketplace option but my memory is not what it once was. I did download the pdf "DeploymentFrameworkForBizTalkDocsV5_7_0.pdf" today. I could find no mention of the supplementary step of installing the VS tools from the gallery in this. Maybe worth adding a note to the section "Installing on a Developer Workstation" on page 12.

**Comment by tfabraham** [comment]
OK -- it was only called out in the changelist.  It may warrant more docs.

I’m unclear now whether you’ve solved the issue, or still having it?

**Comment by RobBowman** [comment]
Yes, after removing versions 5.6 and 6, then installing v5.7, I was able to run GenerateTypedBamApi and ExportBamDefinitionXml. I just checked in control panel and I currently have version 14.0.7015.1000 of Microsoft Access database engine 2010 (108mb) installed. I possible don't need this but having finally got the VM to as state where it's happy - I'll leave it be!
p.s. The new Icons in v5.7 look great!

**Comment by tfabraham** [comment]
OK, great.  v6.0 supports x86 and x64, but that might cause an issue due to the one-or-the-other nature of the Access Runtime.  Maybe you were running the v6.0 MSBuild files without realizing it.  Just guessing... but seems plausible since removing everything and installing v5.7 fixed it.

I'm glad you like the new icons!
