### ISSUE TITLE
Party Agreements

### ISSUE THREAD

**Issue by timdhaeyer** [BTDF/DeploymentFramework#459]
Hi,

On our BizTalk environment we do quite some EDI/AS2 things, so we have quite some parties and agreements configured.
This is interfering a bit with our automatic deployment since ports that are linked to parties can not be removed.
What would be the best way to move forward? We can include the parties in our application binding files, but that would require lot's of maintenance and lot's of environment dependend settings.
On the other hand, that could prove to be usefull when we need to quickly setup a new environment.

What do other people do in this situation. For now we use the automatic deployment only for applications that don't use EDI/AS2, but I would like to have it fully operational for everything.

any help is appreciated. :-)

Kind Regards
Tim

**Comment by PVandenheede** [comment]
Hi Tim, funny to find you here :-)

Keep in mind that when you remove a party/agreement from BizTalk and then add it again, your EDIFACT/X12 control numbers will restart. This is not necessarily something you would want.

In terms of a solution, this is what I did at one of my previous customers:
Instead of linking the send port to an agreement, we dynamically promoted the agreement name, sender name and receiver name in the send port in a pipeline component preceding the EDI assembler.

Please check here for more information on how to do this: 
https://docs.microsoft.com/en-us/biztalk/core/the-role-of-agreements-in-edi-processing 

FYI: it also allows for much more dynamic EDI solutions :-)

**Comment by timdhaeyer** [comment]
Hi Pieter, the integration community in Belgium is not that big. :-)

Thanks for the suggestion! That's indeed a good way to go. Will help us as well when we have multiple agreements for 1 partner.
